apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The application's http port.
  creationTimestamp: 2019-11-19T21:28:35Z
  labels:
    application: openjdk-app
    template: openjdk18-web-basic-s2i
    template.openshift.io/template-instance-owner: 8b3cba23-0b13-11ea-a986-129f2a51a40d
    xpaas: 1.4.14
  name: openjdk-app
  namespace: dev-env
  resourceVersion: "38989"
  selfLink: /api/v1/namespaces/dev-env/services/openjdk-app
  uid: 8b3fa541-0b13-11ea-a986-129f2a51a40d
spec:
  clusterIP: 172.30.90.132
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentConfig: openjdk-app
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
